version: '3.8'
services:
  postgres:
    container_name: microservice_postgres
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=unibo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - /postgresql/data
    networks:
      - ws-network

volumes:
  psql-db-data:

networks:
  ws-network:
