version: '3.8'
services:
  postgres:
    build: ./docker/postgress
    container_name: postgresql
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ms-users
    ports:
      - "5432:5432"
    volumes:
      - /postgresql/data
    networks:
      - ws-network

volumes:
  psql-db-data:

networks:
  ws-network:
